CREATE TABLE APP_USER (
    USER_ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(50),
    PHONE VARCHAR(15)
);

CREATE TABLE SLEEP (
    SLEEP_ID SERIAL PRIMARY KEY,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    DURATION_MIN INT CHECK (DURATION_MIN > 0),
    USER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES APP_USER (USER_ID)
);

CREATE TABLE SLEEP_STAT (
    STAT_ID SERIAL PRIMARY KEY,
    PERIOD_START DATE NOT NULL,
    PERIOD_END DATE NOT NULL,
    AVG_DURATION_MIN INT CHECK (AVG_DURATION_MIN >= 0),
    AVG_QUALITY REAL CHECK (AVG_QUALITY BETWEEN 0 AND 100),
    USER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES APP_USER (USER_ID)
);

CREATE TABLE RECOMMENDATION (
    REC_ID SERIAL PRIMARY KEY,
    REC_TEXT VARCHAR(500),
    CREATED_DATE DATE,
    STAT_ID INT NOT NULL,
    FOREIGN KEY (STAT_ID) REFERENCES SLEEP_STAT (STAT_ID)
);

CREATE TABLE SEARCH_PARAMS (
    PARAMS_ID SERIAL PRIMARY KEY,
    DISTRICT VARCHAR(50),
    HOUSE_TYPE VARCHAR(30),
    MIN_ROOMS INT,
    MIN_AREA_M2 FLOAT,
    MAX_PRICE NUMERIC(10, 2),
    USER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES APP_USER (USER_ID),
    CONSTRAINT DISTRICT_PATTERN CHECK (
        DISTRICT IS NULL
        OR DISTRICT ~ '^[[:alpha:]][[:alpha:][:space:]-]{1,49}$'
    ),
    CONSTRAINT HOUSE_TYPE_PATTERN CHECK (
        HOUSE_TYPE IS NULL
        OR HOUSE_TYPE ~ '^[[:alpha:]][[:alpha:]-]{1,29}$'
    )
);

CREATE TABLE DATA_SOURCE (
    SOURCE_ID SERIAL PRIMARY KEY,
    SOURCE_NAME VARCHAR(40) NOT NULL,
    REGION VARCHAR(30),
    SOURCE_TYPE VARCHAR(15) CHECK (SOURCE_TYPE IN ('DB', 'API', 'SERVICE'))
);

CREATE TABLE PROPERTY_INFO (
    PROPERTY_ID SERIAL PRIMARY KEY,
    DISTRICT VARCHAR(40),
    HOUSE_TYPE VARCHAR(20),
    ROOMS SMALLINT CHECK (ROOMS >= 0),
    AREA_M2 FLOAT CHECK (AREA_M2 > 0),
    RENT_PRICE NUMERIC(10, 2) CHECK (RENT_PRICE > 0),
    SOURCE_ID INT NOT NULL,
    FOREIGN KEY (SOURCE_ID) REFERENCES DATA_SOURCE (SOURCE_ID)
);
