name: Data Schema Code Convention
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  SQLLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code in Repository
        uses: "actions/checkout@v4"
      - name: Start SQL Linter
        run: |
          pip install sqlfluff
          sqlfluff lint $GITHUB_WORKSPACE/schema.sql --dialect postgres

  JSONLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code in Repository
        uses: "actions/checkout@v4"
      - name: Start JSON Linter
        run: |
          npm i -g @prantlf/jsonlint
          jsonlint $GITHUB_WORKSPACE/schema.json

